dist: xenial
language: generic
group: edge
addons:
  apt:
    sources:
      - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ bionic main universe"
    packages:
      - texlive
      - texlive-fonts-extra
      - texlive-lang-german
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-plain-generic
      - texlive-bibtex-extra
      - biber
      - texlive-pictures
      - texlive-publishers
      - texlive-font-utils
      - texlive-luatex
      - ghostscript
      - python-pygments
      - latexmk
      - cm-super

script:
  - cd doc
  - latexmk -pdf -pdflatex=lualatex -latexoption=-shell-escape main.tex
